# Copyright 2025 SegmeCam Contributors
# SPDX-License-Identifier: Apache-2.0
#
# AR Filter Test Assets - Phase 3

# Export all OBJ/MTL files as individual exports for test data dependencies

exports_files([
    "simple_cube.obj",
    "simple_cube.mtl",
    "simple_glasses.obj",
    "simple_glasses.mtl",
    "simple_hat.obj",
    "simple_hat.mtl",
], visibility = ["//visibility:public"])
